### ISSUE TITLE
Development gems

### ISSUE THREAD

**Issue by fladson** [Codeminer42/code42template#3]
Quais gems deverão ser default no development group?

**Comment by lucasbibiano** [comment]
brakeman

**Comment by daniloisr** [comment]
[letter_opener](https://rubygems.org/gems/letter_opener)

**Comment by talyssonoc** [comment]
[rubocop](https://github.com/bbatsov/rubocop)?

**Comment by brunoskonrad** [comment]
[browser sync rails](https://rubygems.org/gems/browser_sync_rails)?

**Comment by IgorMarques** [comment]
[bullet](https://github.com/flyerhzm/bullet)

**Comment by IgorMarques** [comment]
[draper](https://github.com/drapergem/draper) ?

**Comment by brnrdog** [comment]
[pry-rails](https://github.com/rweng/pry-rails)

**Comment by waldyr** [comment]
https://github.com/troessner/reek
