### ISSUE TITLE
MinerDeployer

### ISSUE THREAD

**Issue by talyssonoc** [Codeminer42/code42template#38]
What do you think about using https://github.com/Codeminer42/miner_deployer for the deploys?

**Comment by thiagoa** [comment]
:+1:

**Comment by thiagoa** [comment]
@talyssonoc MinerDeployer is a bit outdated. I was thinking, we already have Heroku deploy working nicely, so there's no need to implement MinerDeployer now. Maybe we could integrate with Gitlab's CI, I'll open up an issue with that.
