### ISSUE TITLE
Front gems

### ISSUE THREAD

**Issue by fladson** [Codeminer42/code42template#4]

**Comment by fladson** [comment]
[autoprefixer-rails](https://github.com/ai/autoprefixer-rails)

**Comment by fladson** [comment]
[flutie](https://github.com/thoughtbot/flutie)

**Comment by fladson** [comment]
[high_voltage](https://github.com/thoughtbot/high_voltage)

**Comment by fladson** [comment]
[normalize-rails](https://github.com/markmcconachie/normalize-rails)

**Comment by brnrdog** [comment]
[paloma](https://github.com/kbparagua/paloma) ? tem uma proposta interessante para modularizar js em rails

**Comment by brnrdog** [comment]
[sassc](https://github.com/sass/sassc-rails) ?
