### ISSUE TITLE
Test gems

### ISSUE THREAD

**Issue by fladson** [Codeminer42/code42template#5]

**Comment by brnrdog** [comment]
[factory girl](https://github.com/thoughtbot/factory_girl_rails)

**Comment by brnrdog** [comment]
(database_cleaner)[https://github.com/DatabaseCleaner/database_cleaner]?

**Comment by brnrdog** [comment]
[rspec](https://www.relishapp.com/rspec/rspec-rails)

**Comment by brnrdog** [comment]
[simple-cov](https://github.com/colszowka/simplecov)
